eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: springcloud-feign-client


server:
  port: 9091

# 开启断路器
feign:
  hystrix:
    enabled: true